# This file was generated by GoReleaser. DO NOT EDIT.
cask "otf-mcp" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "53b7db26d125323cee5852f50260dfba0075477b18893352471a814cf39dd0e2"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "c6e101920308d33a09496f9ec253c2b329c54c77d148f91174ea5c545f7d2d32"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "563a10f8a2b92394c2719f2997cfabe6e5aceaa94ebfca66c5fce1226871b4f2"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "61a00f6bb22ed73440e505c49f8f5fa34ebbf2e6ff7a6684cc0f2312784d0ec7"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-linux-arm64.tar.gz"
    end
  end

  name "otf-mcp"
  desc "MCP server for the OrangeTheory Fitness API — AI-ready class booking"
  homepage "https://github.com/ammiranda/otf_api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otf-mcp"

  # No zap stanza required

end
