# This file was generated by GoReleaser. DO NOT EDIT.
cask "otf-mcp" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "508c48259242094c8ecbb46b591c6d2dcc2c481b5d30fe43b9da894c07f31088"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "82569330197b60c71705b12d6dc91d19ab135a9792d8838b52846de12392ee18"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "86390a6a359037a69557aba28f272873add980f5201828b095b3b933809e81cf"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "83a492ab55b839fd5a6311dc8399b46563df5477abb506b7e62ffaf84d43ce50"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-linux-arm64.tar.gz"
    end
  end

  name "otf-mcp"
  desc "MCP server for the OrangeTheory Fitness API — AI-ready class booking"
  homepage "https://github.com/ammiranda/otf_api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otf-mcp"

  # No zap stanza required

end
