# This file was generated by GoReleaser. DO NOT EDIT.
cask "otf-mcp" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "96b7e370622ad653fb1d5f3a9cf87306cb16d14474182714749e9e5cf6753657"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "3922964c4c262eae2a36a8001417dc7343089c694647b50f74c9411074679593"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20890ac4054e502447e8297860b4fd382afdaa8e9ded5c3fe2cae92c3e3ff68e"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "e4a8fafb2bb8e3f15ee2d75a7a870ff98a78da858365ed75357394f2080101db"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-mcp-linux-arm64.tar.gz"
    end
  end

  name "otf-mcp"
  desc "MCP server for the OrangeTheory Fitness API — AI-ready class booking"
  homepage "https://github.com/ammiranda/otf_api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otf-mcp"

  # No zap stanza required

end
