# This file was generated by GoReleaser. DO NOT EDIT.
cask "otf-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "04674f6cd4da37ec4d095fd9f5ff8be42c8e785a745c2f2d1369a49a15b3336e"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "1290ecf36fa9cacb2b653c2f325a70848d7781118b58ea3b0ec2154f02075dd9"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16b84fa0a4717acab271b176efd3ef7f0fe49cef562415866f52900cc46b82f0"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "06f0300a1e72d5d57725adebe845939054fce729299f3efd9dd07511e8d524b7"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-linux-arm64.tar.gz"
    end
  end

  name "otf-cli"
  desc "CLI for the OrangeTheory Fitness API — browse, book, and manage OTF classes"
  homepage "https://github.com/ammiranda/otf_api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otf-cli"

  # No zap stanza required

end
