# This file was generated by GoReleaser. DO NOT EDIT.
cask "otf-cli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "a1285a26828b845a9bff66c9ea63feec36fb1954b6bd8a082a12637595428dda"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "9ac6495018c00df5aae15ce4039c67c881898e21f57d196da2622217fa665321"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9b4836bca317fb583f84b6f29316a33bf4c102178ec3758d0c5dcd962fe5798b"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "9f0f9bd42abc831e22aca5d30060d93d7aa82be2090fe59bf1cf4801cd66c156"
      url "https://github.com/ammiranda/otf_api/releases/download/v#{version}/otf-cli-linux-arm64.tar.gz"
    end
  end

  name "otf-cli"
  desc "CLI for the OrangeTheory Fitness API — browse, book, and manage OTF classes"
  homepage "https://github.com/ammiranda/otf_api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otf-cli"

  # No zap stanza required

end
